# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Dates
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"

  # custom latex commands
  - trigger: ":tb" # tex block
    replace: "$$\n$|$\n$$"

  - trigger: ":tm" # tex matrix
    replace: "\\begin{bmatrix} $|$ \\end{bmatrix}"

  - trigger: ":tt" # tex exponent
    replace: "^{$|$}"

  - trigger: ":tu" # tex subscript
    replace: "_{$|$}"

  - trigger: ":tf" # tex frac
    replace: "\\frac{$|$}{}"

  - trigger: ":lim" # text limit
    replace: "\\lim_{$|$ \\to }"

  - trigger: ":cases" # bracket
    replace: "\\begin{cases} \n$|$\n \\end{cases}"

  - trigger: ":text" # text
    replace: "\\text{$|$}"

  - trigger: ":ts" # tex sum
    replace: "\\sum_{n=$|$}^{}"

  - trigger: ":p1" # formatted probability
    replace: "\\mathbb P($|$)"    

  - trigger: ":p2" # formatted probability
    replace: "\\mathbb P_{$|$}()"    

  - trigger: ":ev" # formatted expectation
    replace: "\\mathbb E \\left[$|$\\right]"

  - trigger: ":r1"
    replace: "\\mathbb R"

  - trigger: ":rn"
    replace: "\\mathbb R^{$}"

  - trigger: ":ta"
    replace: "\\begin{align*}\n$|$\n\\end{align*}"

  - trigger: ":dv"
    replace: "\\nabla "
  
  - trigger: ":tp" 
    replace: "\\left($|$\\right)"

  - trigger: ":dp"
    replace: "\\langle $|$\\rangle"

  - trigger: ":mn"
    replace: "\\min$|$"

  - trigger: ":mx"
    replace: "\\max$|$"

# obsidian  commands
  - trigger: ":ex"
    replace: "> [!example]"
            
  - trigger: ":thm"
    replace: "> [!theorem]"

  - trigger: ":prf"
    replace: "> [!proof]"

  - trigger: ":def"
    replace: "> [!definition]"
